version: '3.8'

services:
  # Existing services...
  orchestrator:
    build:
      context: .
      dockerfile: docker/Dockerfile.orchestrator
    ports:
      - "5003:5003"
    environment:
      - REDIS_URL=redis://keydb:6379  # Same Redis URL format
      - MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
      - keydb
    volumes:
      - ./chroma_db:/app/chroma_db

  discord-handler:
    build:
      context: .
      dockerfile: docker/Dockerfile.discord_handler
    ports:
      - "5004:5004"
    environment:
      - REDIS_URL=redis://keydb:6379  # Same Redis client libraries work
      - ORCHESTRATOR_API_URL=http://orchestrator:5003/orchestrate
    depends_on:
      - orchestrator
      - keydb

  rag-retriever:
    build:
      context: .
      dockerfile: docker/Dockerfile.rag_retriever
    ports:
      - "5005:5005"
    environment:
      - REDIS_URL=redis://keydb:6379
      - CHROMA_DB_PATH=/app/chroma_db
    depends_on:
      - keydb
    volumes:
      - ./chroma_db:/app/chroma_db

  # KeyDB - Redis-compatible with better performance
  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    command: >
      keydb-server 
      --appendonly yes 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru
      --server-threads 4
      --multi-threading yes
    volumes:
      - keydb_data:/data
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # KeyDB Commander (Redis Commander works with KeyDB)
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:keydb:6379
    depends_on:
      - keydb

  # Existing services...
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  keydb_data:  # KeyDB persistent storage 